### ISSUE TITLE
Update to navigo & new bootstrapping API

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar-developer-tools-content#5]
@x1B, @jonaswjs:

There were these changes in Laxar, which will be pulled when installing dependencies: https://github.com/LaxarJS/laxar/issues/437

Also, navigo was introduced as a router: https://github.com/LaxarJS/laxar/issues/435

Update the `init.js` accordingly.

Note: There is still https://github.com/LaxarJS/laxar/issues/440 which prevents the latest Laxar version to work out-of-the-box.

**Comment by alex3683** [comment]
@jpommerening Version `2.0.0-alpha.20` fixes LaxarJS/laxar#440.

**Comment by jpommerening** [comment]
@alex3683 that version is not published on npm yet, is it?

*\*tries again a minute later\**

oh, ok, nevermind :D

**Comment by alex3683** [comment]
Ehm, ... it is! 😇

**Comment by jpommerening** [comment]
Implemented on `master`
